name: Build

on:
  workflow_dispatch:
  push: 
    branches:
      - master
    paths:
      - "*.go"
      - "Makefile"
      - "!README.md"
      - "!LICENSE"
      - "!.gitignore"

permissions: 
  contents: read

jobs: 
  build:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-22.04, ubuntu-24.04, windows-2019, windows-2022, windows-2025, windows-11-arm, ubuntu-22.04-arm, ubuntu-24.04-arm, macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    name: Build executable (${{ matrix.os }})
    steps:
      - uses: "NetherRealmSpigot/reusable-actions/mcping-golang/build@main"
        with:
          build-ref: ${{ github.ref }}
          golang-version: "^1.24"
          suffix: ${{ matrix.os }}