name: Publish release

on:
  push:
    tags:
      - "v0.0.**"

permissions:
  contents: write

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: "NetherRealmSpigot/reusable-actions/mcping-golang/release@main"
        with:
          tag-ref: ${{ github.ref }}
          golang-version: "^1.24"
          token: ${{ github.token }}